<?php

$blog = $block->getBlogModel();
$postCollection = $blog->getPostCollection();
/**
 * @var \Itransition\Blog\Model\Post $post
 */
foreach ($postCollection as $post): ?>
    <a href="<?= $blog->generateUrl($post->getIdentifier()) ?>">
        <div class="itr-shadow ">
            <h1><?= $post->getTitle() ?></h1>
            <img src="<?= $blog->getImageUrl($post) ?>">
        </div>
    </a>
<?php endforeach; ?>